In [2]:
import torch # importa a biblioteca PyTorch

In [3]:
# criando um tensor 1-D (rank 1)
sample = torch.tensor([10, 11])
sample.shape

torch.Size([2])

O output indica um tensor de 1 dimensão e 2 valores.

In [4]:
# criando um tensor 2-D (rank 2)
x = torch.tensor([[10, 11], [1, 2]])
x.shape

torch.Size([2, 2])

O output indica um tensor com 2 dimensões com 2 elementos em cada (resultando em 4 valores).

In [5]:
# criando outro tensor 2-D
y = torch.tensor([[10], [11]])
y.shape

torch.Size([2, 1])

O output indica um tensor com 2 dimensões, uma com 2 elementos e outra com 2, resultado em 2 valores.

# Visualizando um tensor 3-D

In [7]:
import plotly.graph_objs as go
import plotly.offline as pyo

# criando um tensor 3-D
a = torch.tensor([[[1,2], [3,4]], [[5,6],[7,8]]]) 

# cria uma lista para cada dimensão do vetor, contendo todos as coordenadas possíveis para cada e formando todos os pontos possíveis
x_vals = []
y_vals = []
z_vals = []

for i in range(a.shape[0]): # 1 iteração para cada linha
    for j in range(a.shape[1]): # 1 iteração para cada coluna
        for k in range(a.shape[2]): # 1 iteração para cada camada de profundidade
            x_vals.append(i) # adiciona o valor atual da linha ao ponto
            y_vals.append(j) # adiciona o valor atual da coluna ao ponto
            z_vals.append(k) # adiciona o valor atual da profundidade ao ponto
# criando um scatter plot 3-D com plotly
trace = go.Scatter3d(
    x = x_vals, # define os valores para o eixo x
    y = y_vals, # define os valores para o eixo y
    z = z_vals, # define os valores para o eixo z
    mode = 'markers', # define o tipo de gráfico, que será de marcadores discretos
    marker = dict( # configura os marcadores
        size = 5,
        color = a.flatten(), # define a cor de cada marcador pelo valores no tensor
        colorscale = 'Viridis', # define a escala de cor
        opacity = 0.8
    )
)

# criando o layout para o plot
layout = go.Layout(
    margin = dict(l = 0, r = 0, b = 0, t = 0), # define margem zero para todas as bordas
    scene = dict( # define algumas configurações para o layout
        xaxis = dict(title='Dim-1'), # define as configurações para o eixo x, no caso, só o título
        yaxis = dict(title='Dim-2'), # define as configurações para o eixo y, no caso, só o título
        zaxis = dict(title='Dim-3'), # define as configurações para o eixo z, no caso, só o título
    )
)

# cria a figura final e exibe ela por uma página html
fig = go.Figure(data=[trace], layout=layout)
pyo.plot(fig, filename='tensor.html')
    

'tensor.html'

# Operaçẽos no tensor

In [13]:
x = torch.tensor([[1,2,3,4],[5,6,7,8]])
x.shape

torch.Size([2, 4])

In [14]:
# multiplicação por escalar
x*10

tensor([[10, 20, 30, 40],
        [50, 60, 70, 80]])

In [15]:
# adição de um escalar
x.add(10)

tensor([[11, 12, 13, 14],
        [15, 16, 17, 18]])

In [16]:
# reshape
x.view(4,2)

tensor([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [22]:
# remover dimensões redundantes (de tamanho 1)
a = torch.ones(2, 1, 10) # cria um tensor com valores unitários e dimenões 2x1x10
a

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [18]:
a.shape

torch.Size([2, 1, 10])

In [32]:
squeezed = a.squeeze()
squeezed

tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [33]:
squeezed.shape

torch.Size([2, 10])

In [35]:
# adicionar uma dimensão redundante de tamanho 1
unsqueezed = squeezed.unsqueeze(2) # adiciona uma dim de tamanho 1 na posião 2 de squeezed.shape
unsqueezed

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]]])

In [36]:
unsqueezed.shape

torch.Size([2, 10, 1])

In [40]:
# adicionando dimensões com indexing e None
squeezed[:, None].shape

torch.Size([2, 1, 10])

In [41]:
squeezed[None]

tensor([[[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]]])

In [39]:
squeezed[:,:,None]

tensor([[[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]],

        [[1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.],
         [1.]]])

In [42]:
# multiplicação de matrizes
a = torch.tensor([[1,2,3,4],[5,6,7,8]]) # 2x4
b = torch.tensor([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [10,11,12]
])
torch.matmul(a,b)

tensor([[ 70,  80,  90],
        [158, 184, 210]])

In [43]:
torch.matmul(b,a)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (4x3 and 2x4)

Um erro retorna, pois para multiplicação de matrizes, a ordem importa.

In [48]:
# concatenção de matrizes
x = torch.randn(1,4,5) # gera uma matriz de 1x4x5 com floats aleatórios entre -1 e 1
z = torch.cat([x,x], axis=1) # concatena x com ele mesmo no eixo 1 de x.shape (linhas)
z

tensor([[[-0.8480, -0.8108,  1.2018,  0.4123, -0.9501],
         [ 0.7322,  0.8738, -0.3274, -1.3993, -0.7079],
         [-0.7809,  1.2323,  0.4677,  0.1039,  0.2708],
         [ 0.7062, -0.3774, -1.7304,  0.8567, -1.2657],
         [-0.8480, -0.8108,  1.2018,  0.4123, -0.9501],
         [ 0.7322,  0.8738, -0.3274, -1.3993, -0.7079],
         [-0.7809,  1.2323,  0.4677,  0.1039,  0.2708],
         [ 0.7062, -0.3774, -1.7304,  0.8567, -1.2657]]])

In [47]:
z.shape

torch.Size([1, 8, 5])

In [49]:
# permutação (mudança de ordem das dimensões)
x = torch.rand(20, 10, 30)
z = x.permute(2, 0, 1) # as dimensões de z serão 30x20x10
z.shape

torch.Size([30, 20, 10])